/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as MouthsRouteImport } from './routes/mouths'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as QualificationRouteImport } from './routes/qualification'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SidecarRouteImport } from './routes/sidecar'
import { Route as TapeRouteImport } from './routes/tape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const MouthsRoute = MouthsRouteImport.update({
  id: '/mouths',
  path: '/mouths',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificationRoute = QualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SidecarRoute = SidecarRouteImport.update({
  id: '/sidecar',
  path: '/sidecar',
  getParentRoute: () => rootRouteImport,
} as any)
const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/funnel': typeof FunnelRoute
  '/go-live': typeof GoLiveRoute
  '/mouths': typeof MouthsRoute
  '/optimizer': typeof OptimizerRoute
  '/qualification': typeof QualificationRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/sidecar': typeof SidecarRoute
  '/tape': typeof TapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/funnel': typeof FunnelRoute
  '/go-live': typeof GoLiveRoute
  '/mouths': typeof MouthsRoute
  '/optimizer': typeof OptimizerRoute
  '/qualification': typeof QualificationRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/sidecar': typeof SidecarRoute
  '/tape': typeof TapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/funnel': typeof FunnelRoute
  '/go-live': typeof GoLiveRoute
  '/mouths': typeof MouthsRoute
  '/optimizer': typeof OptimizerRoute
  '/qualification': typeof QualificationRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/sidecar': typeof SidecarRoute
  '/tape': typeof TapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/funnel'
    | '/go-live'
    | '/mouths'
    | '/optimizer'
    | '/qualification'
    | '/risk'
    | '/settings'
    | '/sidecar'
    | '/tape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contracts'
    | '/funnel'
    | '/go-live'
    | '/mouths'
    | '/optimizer'
    | '/qualification'
    | '/risk'
    | '/settings'
    | '/sidecar'
    | '/tape'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/funnel'
    | '/go-live'
    | '/mouths'
    | '/optimizer'
    | '/qualification'
    | '/risk'
    | '/settings'
    | '/sidecar'
    | '/tape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRoute
  FunnelRoute: typeof FunnelRoute
  GoLiveRoute: typeof GoLiveRoute
  MouthsRoute: typeof MouthsRoute
  OptimizerRoute: typeof OptimizerRoute
  QualificationRoute: typeof QualificationRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  SidecarRoute: typeof SidecarRoute
  TapeRoute: typeof TapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mouths': {
      id: '/mouths'
      path: '/mouths'
      fullPath: '/mouths'
      preLoaderRoute: typeof MouthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualification': {
      id: '/qualification'
      path: '/qualification'
      fullPath: '/qualification'
      preLoaderRoute: typeof QualificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidecar': {
      id: '/sidecar'
      path: '/sidecar'
      fullPath: '/sidecar'
      preLoaderRoute: typeof SidecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRoute,
  FunnelRoute: FunnelRoute,
  GoLiveRoute: GoLiveRoute,
  MouthsRoute: MouthsRoute,
  OptimizerRoute: OptimizerRoute,
  QualificationRoute: QualificationRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  SidecarRoute: SidecarRoute,
  TapeRoute: TapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
